### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wdsjhskj** [falseL/mkv-track-remover#1]
建议加一个指定MKVToolNix路径的功能和打包成exe

**Comment by falseL** [comment]
1. 加上了指定路径的功能，但是pypi上最新的pymkv只有1.0.8，1.0.9才有指定路径的功能，所以如果需要本地build的话现在需要指定github来装
2. 打包好了：https://github.com/falseL/mkv-track-remover/releases/tag/v0.1
